# Generated by Django 2.1.5 on 2021-05-21 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0001_initial'),
        ('notifications', '0003_remove_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_post', to='Chats.Message'),
        ),
    ]
